### ISSUE TITLE
Using pubchempy / urllib behind proxy

### ISSUE THREAD

**Issue by timothymillar** [mcs07/PubChemPy#11]
I'm using PubChem from behind a proxy (Research institute).
I ran into error Errno 65:

```
>>> import pubchempy as pug
>>> compound = pug.Compound.from_cid(1423)
...
URLError: <urlopen error [Errno 65] No route to host>
```

A relatively simple fix is to specify proxy information via [urllib](https://docs.python.org/3.1/howto/urllib2.html#id15):

```
>>> import urllib
>>> import pubchempy as pug
>>> proxies = {'http': 'http://<proxy.address>:<port>',
...            'https': 'https://<proxy.address>:<port>'}
>>> proxy_support = urllib.request.ProxyHandler(proxies)
>>> opener = urllib.request.build_opener(proxy_support)
>>> urllib.request.install_opener(opener)
>>> compound = pug.Compound.from_cid(1423)
>>> compound
Compound(1423)
```

The issue is that there is no mention of specifying proxy information in the PubChem documentation.
Addressing this in your documentation (even just a link to the [urllib docs](https://docs.python.org/3.1/howto/urllib2.html#id15)) could save others a lot of time.

**Comment by mcs07** [comment]
Thanks for the tip!
