### ISSUE TITLE
get_compounds no longer returns multiple hits

### ISSUE THREAD

**Issue by supern8ent** [mcs07/PubChemPy#12]
On the getting started page there is this snippet:
>>> results = pcp.get_compounds('Glucose', 'name')
>>> print results
[Compound(79025), Compound(5793), Compound(64689), Compound(206)]

If I run that now, I only get one compound. Multiple compounds would be my preferred behavior. For example if I request '2-nonenal' I'd like to get both the isomers.

version 1.0.3

**Comment by mcs07** [comment]
I asked the PubChem team about this, and Paul Thiessen confirmed that for some very common names, they have manually created a filtered whitelist of human-chosen CIDs with the intention of reducing confusion about which is the 'right' result.

Unfortunately it isn't directly possible to return to the previous behaviour, but he had a good suggestion for a workaround: Search for Substances with that name (completely unfiltered) and then get the compounds that are derived from those substances.

There area a few different ways you can do this using PubChemPy, but the easiest is probably using the `get_cids` function:

    >>> pcp.get_cids('2-nonenal', 'name', 'substance', list_return='flat')
    [17166, 5283335, 5354833]

This searches the substance database for '2-nonenal', and gets the CID for the compound associated with each substance. By default, this returns a mapping between each SID and CID, but the `list_return='flat'` parameter flattens this into just a single list of unique CIDs.

You can then use `Compound.from_cid` to get the full Compound record, equivalent to what is returned by `get_compounds`:

    >>> cids = pcp.get_cids('2-nonenal', 'name', 'substance', list_return='flat')
    >>> [pcp.Compound.from_cid(cid) for cid in cids]
    [Compound(17166), Compound(5283335), Compound(5354833)]

**Comment by supern8ent** [comment]
Thanks so much @mcs07! 
Also, sorry for the late reply - I don't check this email addy often enough.
