### ISSUE TITLE
TypeError when trying to download a compund with None as cid

### ISSUE THREAD

**Issue by llazzaro** [mcs07/PubChemPy#13]
I was doing a search with get_compounds with smiles string and I got a compound with None as cid.
I know it could not make sense to ask for a compound with a cid as None, but we could do a check on the cid formats.
I will analyse why get_compounds returned a Compound object with None as cid later.
I can provide a fix to this issue and to get_compunds if there is a bug there also (I will open other ticket in that case)

This was the error:

```python
Traceback (most recent call last):
  File "convert_old_ligand_to_pubchem.py", line 29, in <module>
    pcp.download('sdf', temp_filename, pubchem_ligand.cid, 'cid')
  File "/home/leonardo/workspace/PubChemPy/pubchempy.py", line 450, in download
    response = get(identifier, namespace, domain, operation, outformat, searchtype, **kwargs)
  File "/home/leonardo/workspace/PubChemPy/pubchempy.py", line 287, in get
    response = request(identifier, namespace, domain, operation, output, searchtype, **kwargs).read()
  File "/home/leonardo/workspace/PubChemPy/pubchempy.py", line 247, in request
    identifier = ','.join(str(x) for x in identifier)
TypeError: 'NoneType' object is not iterable
```

**Comment by mcs07** [comment]
By the way, it is expected to sometimes return a compound without a CID for a SMILES input. It happens when you provide a valid SMILES that doesn't match any compound record in PubChem. In these cases, `get_compounds` returns a compound record that has been generated on the fly that contains calculated properties but no CID.
