### ISSUE TITLE
Discrepancy between the CACTVS fingerprint spec and Compound.fingerprint

### ISSUE THREAD

**Issue by coreymhudson** [mcs07/PubChemPy#15]
The specifications for the compound fingerprints suggest different coding then the program reports.
**For example:**
CID _7844_'s fingerprint should be:

'AAADccBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAACACAAAACAAAAAACAACBCAAAAAAAgAAAIAAAAAAgAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' 

This is according to both the PubChem spec and the PubChem download page.
However the fingerprint collected from the program is:

'00000371C06000000000000000000000000000000000000000000000000000000000000000000018000000000008008000000200000000008000204200000000002000000800000000080000000001000000000000000000000000000000000000000000000000000000000000000000000000'

My guess is that this is a different encoding scheme. But this is different from the spec at ftp://ftp.ncbi.nlm.nih.gov/pubchem/specifications/pubchem_fingerprints.txt, which makes it hard to connect this fingerprint to the actual properties.

**Comment by hkmztrk** [comment]
Hello,

I'm also having a similar problem,

bin(int(coumarin.fingerprint, 16)), 

the function above outputs 900 bits, but Pubchem specifications say that, fingerprints are 881 bits in length ( http://astro.temple.edu/~tua87106/list_fingerprints.pdf). Therefore, how can I get 881 bits format from pubchempy’s fingerprint function?
