### ISSUE TITLE
PubChemPy stopped working today

### ISSUE THREAD

**Issue by daochenw** [mcs07/PubChemPy#31]
Hi there,

I have been using PubChemPy for a while and it's been working great until today when commands that used to work don't anymore. For example, the simple command `compounds = pcp.get_compounds('methane', 'name', record_type='3d')` gives the error URLError:

>  <urlopen error [Errno 8] nodename nor servname provided, or not known>

I suspect there's been some changes to PubChem itself?

**Comment by mcs07** [comment]
Things look OK for me. The error message suggests network connectivity issues - it could have been a temporary problem with the PubChem servers or it may be a problem with your local network.

Are you able to open this link:
https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/methane/JSON?record_type=3d

**Comment by daochenw** [comment]
Thanks for replying quickly! So I just tried and I cannot. Do you know how I can fix this?

**Comment by mcs07** [comment]
I think you will need to contact the pubchem support team: https://pubchemdocs.ncbi.nlm.nih.gov/contact
