### ISSUE TITLE
search by name function is not working for tetrabamate

### ISSUE THREAD

**Issue by MALKAKER** [mcs07/PubChemPy#32]
Hi, 
First of all, thanks for the nice package, it is very helpful for me.
I have a problem with the search function- get_compounds(Compound_Name, 'name')  when I'm trying to fetch "tetrabamate" details and get no results, however, I had tried directly the pubchem API, and it finds the relevant cids I need.

the line code:
cs = get_compounds('tetrabamate', 'name') <- this line perfectly works  for the other molecules.

I will be happy if you can help me to solve this problem.

Thank you

**Comment by khoivan88** [comment]
@MALKAKER : you probably have figured it out but it seems to work fine for me right now?! Perhaps, the Pubchem server was down at the time?

```python
>>> import pubchempy as pcp
>>> pcp.get_compounds('tetrabamate', 'name') 
[Compound(57394584)]
```
