### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by jacobdp24** [mcs07/PubChemPy#34]
![sslerror](https://user-images.githubusercontent.com/27260777/50334619-bac03700-04bd-11e9-8f9f-f1d8f93f0f20.jpg)

getting a SSL error and an urllib error. I'm just following the examples in the documentation so I'm not sure how to fix it. I've tried using the API on two different networks and I am still getting this error. Does it have something to do with the pubchem servers or is this on my end?

thanks

**Comment by jacobdp24** [comment]
for those who run into this error, it seems to be macOS specific. To fix it, simply go to your finder, find where your version of python is stored, and double click the Install Certificates.command file
![screenshot 2018-12-21 at 5 43 41 pm](https://user-images.githubusercontent.com/27260777/50369305-015a7380-0548-11e9-8571-db33886b5a46.jpg)

**Comment by mcs07** [comment]
See also #118
