### ISSUE TITLE
Search by CAS #?

### ISSUE THREAD

**Issue by theman0605** [mcs07/PubChemPy#37]
Hello.  I am wondering if there is a way to use the PubChemPy to search by CAS #?

Thanks,

Stan

**Comment by mcs07** [comment]
I don't believe CAS registry numbers are officially supported by PubChem (possibly for legal reasons) but many depositors include them as a synonym. Therefore you can just search by name and often it will work:

    >>> import pubchempy as pcp
    >>> results = pcp.get_compounds('50-78-2', 'name')
    >>> print(results)
    [Compound(2244)]
    >>> print(results[0].canonical_smiles)
    CC(=O)OC1=CC=CC=C1C(=O)O

**Comment by theman0605** [comment]
Thanks for the quick response Matt.  I'll give it a shot.

Stan
