### ISSUE TITLE
substance SID is being returned as compound CID

### ISSUE THREAD

**Issue by atloo1** [mcs07/PubChemPy#44]
`get_compounds('CC(=CCCC(C)(C1CCC2(C1C(CC3C2(CCC4C3(CCC(C4(C)C)OC5C(C(C(CO5)O)O)OC6C(C(C(C(O6)CO)O)O)O)CO)C)O)C)O)C','smiles')` returns `[Compound(15590165)]`.

The [equivalent web lookup](https://pubchem.ncbi.nlm.nih.gov/#query=15590165) shows one result w/ a substance SID of 15590165. The true compound CID is 10562613.

**Comment by BalooRM** [comment]
CID (compound) 15590165 is the correct result for the indicated SMILES. 

SID 15590165 (https://pubchem.ncbi.nlm.nih.gov/substance/15590165) and CID 10562613 (https://pubchem.ncbi.nlm.nih.gov/compound/10562613) are equivalent with canonical SMILES = C=C1C(OC(C1O)O)COC(=O)C2=CC=CC=C2.
