### ISSUE TITLE
How to get cas no/?

### ISSUE THREAD

**Issue by machinexa2** [mcs07/PubChemPy#61]
How to get CAS NO of a compound

**Comment by nbehrnd** [comment]
> How to get CAS NO of a compound
> 

The CAS RN is one of the synonyms assigned to identify the entry, and
(to best of my knowledge) there is no dedicated single tag (yet) in
PubChem.  Thus (on the example of aspirin), it is among the list
provided by the MWE

```
from pubchempy import get_compounds, Compound
comp = Compound.from_cid(2244)
print(comp.synonyms)
``

Inside this list of strings, CAS RN is one following the regex pattern
of

```
^\d{2,7}-\d{2}-\d{1}$
```

where the last decimal is a modulo check digit.  Note the following
limitations (not exhaustive):
+ not all entries in PubChem are assigned /a/ CAS RN
+ there may be more than one single CAS RN per chemical composition
  (e.g., polymorphic crystal phases like TiO2 as rutile or anatas,
  and some of the more complex organic molecules)

HTH

**Comment by machinexa2** [comment]
Oh wow. Awesome. Could you please tell me regex of EC number and unii too?

**Comment by machinexa2** [comment]
@nbehrnd

**Comment by machinexa2** [comment]
> + not all entries in PubChem are assigned /a/ CAS RN
 > + there may be more than one single CAS RN per chemical composition
>  (e.g., polymorphic crystal phases like TiO2 as rutile or anatas,
 > and some of the more complex organic molecules)

hmm

**Comment by machinexa2** [comment]
Close the issue, may update documentation on how to get CAS , European Community (EC) Number, NSC Number, UNII, DSSTox Substance ID etc

This module is absolutely fine at doing its job. It would be better if there was internal code to serparate out "Other identifiers" from compound.synonyms by using regex and creating a separate attribute for each. If not found those identifiers then the attribute should be "" by default. Not a necessity but the module would be better.

**Comment by nbehrnd** [comment]
> Close the issue, may update documentation on how to get CAS , European Community (EC) Number, NSC Number, UNII, DSSTox Substance ID etc

Depending on the privileges assigned, either the author of the issue
or the owner of the project may close an issue.  Since I'm neither
one (just one in the aisle with a pending pull requests to update
some of the documentation to Python 3), I'm unable to close the
thread, but perhaps you?

Re the numbers in question:  It probably would help to collect
typical format references of these to know what pattern to expect.
E.g.

```
|---------------------+----------------------------+-------------|
| identifier          | string pattern             | a reference |
|---------------------+----------------------------+-------------|
| CAS RN              | \d{2-7}-\d{2}-\d           | [1]         |
| EC number           | \d{3}-\d{3}-\d             | [2]         |
| NSC number          | \d+                        | [3]         |
| UII number          | "UNII: " and [A-Z,0-9]{10} | [4], [5]    |
| DSSTOx substance ID | "DTXSID" and \d{7}         | [6], [7]    |
|---------------------+----------------------------+-------------|

[1] https://en.wikipedia.org/wiki/CAS_Registry_Number
[2] https://en.wikipedia.org/wiki/European_Community_number
[3] https://www.wikidata.org/wiki/Property:P2840

[4] https://en.wikipedia.org/wiki/Unique_Ingredient_Identifier
[5] https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7779023/

[6] https://www.wikidata.org/wiki/Property:P3117
[7] https://comptox.epa.gov/dashboard/dsstoxdb/results?search=benzene

```

If you need the CAS e.g., to collect safety data sheet/SDS, give

https://github.com/khoivan88/find_sds

a chance.  Depending on your local setup, you might need to substitute
in file ```requirements.txt``` the line ```idna==3.1``` by ```idna```
to get through the installation (one reason to use a virtual
environment backed e.g., by Python 3.9.2), before it is fully
functional.

> 
> This module is absolutely fine at doing its job. It would be better if there was internal code to serparate out "Other identifiers" from compound.synonyms by using regex and creating a separate attribute for each. If not found those identifiers then the attribute should be "" by default. Not a necessity but the module would be better.
> 

This is .true.

**Comment by khoivan88** [comment]
> If you need the CAS e.g., to collect safety data sheet/SDS, give https://github.com/khoivan88/find_sds a chance. Depending on your local setup, you might need to substitute in file ```requirements.txt``` the line ```idna==3.1``` by ```idna``` to get through the installation (one reason to use a virtual environment backed e.g., by Python 3.9.2), before it is fully functional.


@nbehrnd ah, thank you for pointing to my library. Yeah, I do need to come back and update some of the requirement packages. Thank you for pointing that out. Hope that works for you!

**Comment by machinexa2** [comment]
@nbehrnd ok i am closing the issue for now
