### ISSUE TITLE
API down for SMILES Search?

### ISSUE THREAD

**Issue by jannisborn** [mcs07/PubChemPy#64]
Previously functioning code using `get_compounds`  with the smiles argument is currently disfunctional. 

For example:
 ```py
get_compounds('C1=CC2=C(C3=C(C=CC=N3)C=C2)N=C1', 'smiles')
```

raises an `pubchempy.BadRequestError`. This does not happen when searching for `name` and also not for substructure searches.

Possible reason: A bug on pubchem side: The UI seems to have trouble standardizing SMILES atm: https://pubchem.ncbi.nlm.nih.gov/#query=C1=CC2=C(C3=C(C=CC=N3)C=C2)N=C1

What's going on here?

**Comment by nbehrnd** [comment]
A couple of minutes ago, I went through the Jupyter-notebooks of this
project. Book "2-getting-started.ipynb" includes a SMILES-based
search, which is working (even in Python 3).  Can you replicate this
on a computer accessible to you?

**Comment by jannisborn** [comment]
The same code that was raising the error before (executed in the same env) now works fine again and gives the same result that you report. 
Seems like this was an API outage on pubchem side.
