### ISSUE TITLE
Search with InChI and InChI key not working

### ISSUE THREAD

**Issue by voidpunk** [mcs07/PubChemPy#66]
Search with InChI and InChI key not working with ```pubchempy.get_compounds()``` (tried with many different compounds copying the codes from PumChem.

Searching for InChI gives:
```
'PUGREST.BadRequest: error: '
2022-01-16 21:20:43.003 'PUGREST.NotFound: No CID found that matches the given InChI key'
```

Searching for InChI key gives:
```
'PUGREST.NotFound: No CID found that matches the given InChI key'
```

**Comment by voidpunk** [comment]
Sorry, it was just me being dumb (a bug in my code), everything works perfectly guys :sweat_smile:

**Comment by nbehrnd** [comment]
As a MWE:

```python
import pubchempy as pcp

entry = results.get_compounds("InChI=1S/C6H12O6/c7-1-2-3(8)4(9)5(10)6(11)12-2/h2-11H,1H2/t2-,3-,4+,5-,6?/m1/s1", "inchi")
print(entry)
```
yields
```
[Compound(5793)]
```

But be aware, without fixed H-layer (and non-standard InChI), you might not discern e.g., between 2-hydroxy pyridine and its tautomeric form, the pyridone.
```
