### ISSUE TITLE
Can not generate SMILES of compounds from known CAS numbers

### ISSUE THREAD

**Issue by MathewGolding** [mcs07/PubChemPy#82]
Hello, I recently began using PubChemPy, and thank you for creating this incredible platform! I am attempting to find the SMILES of over 500 compounds via the `get_compound()` function however the only data for my input into the function is a I have is a list of CAS numbers. As far as I can tell, PubChemPy has no way of pulling a compound from the CAS number using the `get_compound()`  function as CAS numbers are not a valid input for this function.
i.e. I have the CAS number "3586-12-7" yet there is not a valid input for this value into the `get_compound()` function

Any help resolving this is massively appreciated!

**Comment by nbehrnd** [comment]
In virtual environment of Python, amended by `pirpy` (version 1.0.2 from [pypi](https://pypi.org/project/CIRpy/), I just run the following conversions with the CAS of the [example here](https://github.com/Aropha/get-chemical-smiles-by-cas-or-name); your compound; glucose and fructose as reported by Wikipedia's property boxes.  It could be a suitable tool to extend from here:

```shell
$ python
Python 3.11.7 (main, Dec  8 2023, 14:22:46) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cirpy
>>> 
>>> data = ['108-95-2', '3586-12-7', '50-99-7', '57-48-7']
>>> 
>>> for entry in data:
...     cirpy.resolve(entry, 'smiles')
... 
'Oc1ccccc1'
'Nc1cccc(Oc2ccccc2)c1'
'OCC1OC(O)C(O)C(O)C1O'
'OC[C@@H](O)[C@@H](O)[C@H](O)C(=O)CO'
>>> 
```

**Comment by MathewGolding** [comment]
Tried out CIRpy as recommended by nbehrnd above. 
Whilst it was, for the most part, successful I still lack the SMILES of roughly 70 compounds. Is there anything else I can use, preferably with PubChemPy to get these SMILES?

**Comment by nbehrnd** [comment]
Well, it depends a bit on the chemicals behind the CAS number.

- some chemical suppliers equally provide a SMILES string, buried in the description of properties.  This is practice is not consistent among all suppliers, the algorithm to assign a SMILES string can be a different one each time.  See e.g., [Sigma](https://www.sigmaaldrich.com/US/en/product/sial/g5767#product-documentation) about one form of glucose:

   ![example_sigma](https://github.com/mcs07/PubChemPy/assets/19709084/51e020c1-1251-444f-adb4-ccc8e1b89d63)

- the English edition of Wikipedia describes chemicals with their CAS number (property pox).  If you have the chemical name of the structures (or the [sub]structure), you can tap into a set of about 22k chemicals (if I remember correctly); the [Wikipedia Chemical Structure explorer](https://wikipedia.cheminfo.org/) can be of help here.

- around/after Wikipedia and ACS/The American Chemical Society settled an agreement to use the CAS registry numbers in Wikipedia, ACS started a project "common chemistry".  The summaries' web addresses follow a pattern like https://commonchemistry.cas.org/detail?cas_rn=50-99-7.  Speculation: programmatic consultation and harvest of the SMILES from there could be automated (Python's [beautifulsoup](https://pypi.org/project/beautifulsoup4/), or an other package of your preference).  Coverage by the number of CAS entries is considerably larger (once advertised to include approx. 500k records) and still free.

- chemspider by the Royal Society of Chemistry can be queried e.g., by a pattern like http://www.chemspider.com/Search.aspx?q=50-99-7, or with an API proper ([link](https://developer.rsc.org/)).  As you see for the results on the example of glucose, there may be multiple structures per CAS (well, ...) but from from a results page like [this](http://www.chemspider.com/Chemical-Structure.71358.html?rid=8cda979e-456b-4891-8921-7afbf055b19b&page_num=0), below the icon of the floppy disc is a .mol file which can be processed further (*vide infra*).  The database claims to store 100 million records.

----

- If you work for a university, or/and have access to a research library with a paid subscription to databases like chemical abstracts/SciFinder scholar (by ACS), or Reaxys (provided by Elsevier), you can perform an individual search by CAS number and request the output of a .mol/.sdf file.  An application like [RDKit](http://rdkit.org/), or [openbabel](https://github.com/openbabel/openbabel/releases) can then convert (batches of) them into one form of SMILES.

**Comment by khoivan88** [comment]
@MathewGolding , I made something that lookup pubchem cid based on different identifier (CAS, smiles, inchi, inchi_key). Maybe you can draw to your application: https://github.com/khoivan88/pka_lookup/blob/9705117d70e9162fe4c410d5fa884d550f02bad2/src/pka_lookup_pubchem.py#L44

README: https://github.com/khoivan88/pka_lookup/tree/master
